
# build settings
markdown: kramdown
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme


title: Game Play Scenario
description: Asha Empire is a strategy-based, FPS and RPG game that takes place in a vast and dynamic world.
